<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="Common/lib/bootstrap-switch/bootstrap-switch.css" rel="stylesheet">
<link rel="stylesheet"href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">

<!-- jQuery library -->
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="Common/lib/bootstrap-switch/bootstrap-switch.js"></script>
