<table class="table table-custom table-responsive table-bordered table-condensed">
	<tr>
	 <th colspan="6" style="color:black;width:32%;font-size:12px !important;">Re-Forecast Trade Analysis Summary</th>
	</tr>
	<tr style="background-color:white;color:black;">
		<td colspan="2">
			<select class="form-control input-sm" name="reForcast">
				<option value="">Select Neutral Factor Indicator</option>
				<option value="0">0 - Neutral Factor</option>
				<option value="1">1 - Neutral Factor</option>
				<option value="2">2 - Neutral Factor</option>
				<option value="3">3 - Neutral Factor</option>
				<option value="4">4 - Neutral Factor</option>			 
				<option value="5">5 - Neutral Factor</option>
				<option value="6">6 - Neutral Factor</option>
				<option value="7">7 - Neutral Factor</option>
				<option value="8">8 - Neutral Factor</option>		
				<option value="9">9 - Neutral Factor</option>
				<option value="10">10 - Neutral Factor</option>
				<option value="11">11 - Neutral Factor</option>
				<option value="12">12 - Neutral Factor</option>			 
				<option value="13">13 - Neutral Factor</option>
				<option value="14">14 - Neutral Factor</option>
				<option value="15">15 - Neutral Factor</option>
				</select>
		</td>
		<td colspan="4">
			<button type="submit" value="Reforecast" name="Action" class="btn btn-block btn-default btn-md"><span class="glyphicon glyphicon-save"></span>&nbsp;Re-Forecast Trade</button>
		</td>
	</tr>
</table>
