<header class="navbar navbar-custom navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
	<div class="container">
		<div class="navbar-header">
				<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"> 
				<span class="sr-only">Toggle navigation</span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
			</button>
			<a href="" class="navbar-brand navbar-left"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;<strong>Detroit Federation of Teachers</strong></a> 
			</div>
			<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
				<ul class="nav navbar-nav">
				<li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Members <b class="caret"></b></a>
				<ul class="dropdown-menu" role="menu">
				<li><a href="">Member Maintenance</a></li>
				</ul>
			</li>
			<li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
				<ul class="dropdown-menu" role="menu">
				<li><a href="">Mailing Labels</a></li>
				<li><a href="">Member Badges</a></li>
				<li><a href="">Member Listing</a></li>
				<li><a href="">Member Fees and Status</a></li>
				</ul>
			</li>
		</nav>
	</div>
</header>