<header class="navbar navbar-custom navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <a href="./" class="navbar-brand">IGBL 2016-2017</a> </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
                  <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Players <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="transelect.asp" target="_self"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;Free Agents/Rentals/Waivers</a></li>
              <li><a href="tradeanalyzer.asp" target="_self"><i class="fa fa-exchange" aria-hidden="true"></i>&nbsp;Submit Trade Offers</a></li>
              <li><a href="ontheblock.asp" target="_self"><i class="fa fa-shopping-cart" aria-hidden="true"></i>&nbsp;OTB</a></li>
							<li><a href="playerSearch.asp" target="_self"><i class="fa fa-search" aria-hidden="true"></i>&nbsp;Search</a></li>
							<li><a href="maintainRoster.asp" target="_self"><i class="fa fa-road" aria-hidden="true"></i>&nbsp;Waive Players</a></li>
              <li><a href="waivers_priority.asp"><i class="fa fa-sort-numeric-asc" aria-hidden="true"></i>&nbsp;Waiver Priority</a></li>
            </ul>
          </li>
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
							<li><a href="finreports.asp" target="_self"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;Financials</a></li>
              <li><a href="rosters.asp"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;Rosters</a></li>
            </ul>
          </li>
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lineups <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="lineups.asp" target="_self"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;Submit New Lineups</a></li>
              <li><a href="viewLineups.asp" target="_self"><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;Review My Lineups</a></li>
            </ul>
          </li>
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stats & Info <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="previous_box_scores.asp"><i class="fa fa-calculator" aria-hidden="true"></i>&nbsp;Box Scores</a></li>
              <li><a href="standings.asp"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;Standings</a></li>
              <li><a href="igblsked.asp"><i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;IGBL Schedule</a></li>
              <li><a href="gamegrid.asp"><i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;Game Grid</a></li>
              <li><a href="emailtheleague.asp"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>&nbsp;Email the League</a></li>
							<li><a href="contacts.asp"><i class="fa fa-users"></i>&nbsp;Contacts</a></li>
							</ul>
          </li>
				</ul>	
        <ul class="nav navbar-nav">
          <li><a href="myigbl.asp"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;MyIGBL</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="login.asp"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Logoff</a></li>
        </ul>
    </nav>
  </div>
</header>