					<table class="table table-custom-black table-responsive table-bordered">
						<tr>
							<th colspan="2">SCORING RULES</th>
						</tr>
						<tr>
							<th class="big" style="width:50%;background-color:white;">Blocked Shots</th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;">2</td>
						</tr>
						<tr>
							<th class="big" style="width:50%;background-color:white;">Assists</th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;"><span style="color:#9a1400;">1.5</span</td>
						</tr>
						<tr>
							<th class="big" style="width:50%;background-color:white;">Rebounds</th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;"><span style="color:#9a1400;">1.25</span></td>
						</tr>
						<tr>
							<th class="big" style="width:50%;background-color:white;">Points Scored</th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;">1</td>
						</tr>
						<tr>
							<th class="big" style="width:50%;background-color:white;">Steals </th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;">2</td>
						</tr>
						<tr>
							<th class="big" style="width:50%;">3 Point Shots Made </th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;">1</th>
						</tr>
						<tr>
							<th class="big" style="width:50%;">Turnovers </th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;">-1</td>
						</tr>
						<tr>
							<th class="big" style="width:50%;">Triple Double</span></th>
							<td class="big" style="width:50%;text-align:center;background-color:white;font-size:12px;"><span style="color:#9a1400;">3</span></td>
						</tr>
						<tr>
							<th colspan="2">GAME TIE BREAKER RULES</th>
						</tr>
						<tr>
							<td colspan="2"style="width:50%;text-align:left;">
								<ol>
									<li class="big">Team with the least turnovers</li>
									<li class="big">Team with the most steals</li>
									<li class="big">Team with the most blocks</li>
									<li class="big">Team with the most 3-pointers</li>
									<li class="big">Team with the most rebounds</li>
									<li class="big">Team with the most assists</li>
									<li class="big">Team with the most points</li> 
									<li class="big">Home Team</li>
									<li class="big"><span class="badgeTie">Category Used to Break the Tie</span></li>
								</ol>
							</td>
						</tr>
					</table>