  <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <a href="./" class="navbar-brand">IGBL 2014-2015</a> </div>
      <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <ul class="nav navbar-nav">
		  <li><a href="transelect.asp?var_pos=ALL">ALL</a></li>
		  <li><a href="transelect.asp?var_pos=CEN">CEN</a></li>
          <li><a href="transelect.asp?var_pos=FOR">FOR</a></li>
          <li><a href="transelect.asp?var_pos=FC">F-C</a></li>
          <li><a href="transelect.asp?var_pos=GUA">GUA</a></li>
          <li><a href="transelect.asp?var_pos=GF">G-F</a></li>
          <li><a href="transelect.asp?var_pos=Today">Today</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="myigbl.asp?ownerid=<%= ownerid %>"><span class="glyphicon glyphicon-home"></span>&nbsp;MyIGBL</a></li>
        </ul>
      </nav>
    </div>
  </header>